kertnik05/LVA

app/Http/Controllers/API/RoleController.php
app/Http/Controllers/API/UserController.php
app/Http/Requests/StoreRoleRequest.php
app/Http/Requests/StoreUserRequest.php
app/Http/Requests/UpdateRoleRequest.php
app/Http/Requests/UpdateUserRequest.php
app/Http/Resources/RoleResource.php
app/Http/Resources/UserResource.php
app/Models/Role.php
app/Models/User.php
database/factories/RoleFactory.php
database/factories/UserFactory.php
database/migrations/2020_10_13_160649_create_roles_table.php
database/migrations/2020_10_13_180409_create_users_table.php
database/seeders/DatabaseSeeder.php
database/seeders/RoleSeeder.php
database/seeders/UserSeeder.php
routes/api.php

User & Role CRUD

---

app/Http/Controllers/API/StudentRemarkController.php
app/Http/Requests/StoreStudentRemarkRequest.php
app/Http/Requests/UpdateStudentRemarkRequest.php
app/Http/Resources/StudentRemarkResource.php
app/Models/StudentRemark.php
database/factories/StudentRemarkFactory.php
database/migrations/2020_10_27_224345_create_student_remarks_table.php
database/seeders/StudentRemarkSeeder.php
routes/api.php

StudentRemark CRUD

---

app/Http/Controllers/API/GuardianController.php
app/Http/Controllers/API/StudentController.php
app/Http/Requests/StoreGuardianRequest.php
app/Http/Requests/StoreStudentRequest.php
app/Http/Requests/UpdateGuardianRequest.php
app/Http/Requests/UpdateStudentRequest.php
app/Http/Resources/GuardianResource.php
app/Http/Resources/StudentResource.php
app/Models/Guardian.php
app/Models/Student.php
database/factories/GuardianFactory.php
database/factories/StudentFactory.php
database/migrations/2020_10_27_231043_create_students_table.php
database/migrations/2020_10_27_231111_create_guardians_table.php
database/migrations/2020_10_27_231525_create_guardian_student_table.php
database/seeders/GuardianSeeder.php
database/seeders/StudentSeeder.php
routes/api.php

Student and Guardian CRUD

---

app/Http/Controllers/API/AcadYearController.php
app/Http/Requests/StoreAcadYearRequest.php
app/Http/Requests/UpdateAcadYearRequest.php
app/Http/Resources/AcadYearResource.php
app/Models/AcadYear.php
database/factories/AcadYearFactory.php
database/migrations/2020_11_03_034233_create_acad_years_table.php
database/seeders/AcadYearSeeder.php
database/seeders/DatabaseSeeder.php
routes/api.php

Acadyear api crud 

---

app/Http/Controllers/API/ProspectusController.php
app/Http/Requests/StoreProspectusRequest.php
app/Http/Requests/UpdateProspectusRequest.php
app/Http/Resources/ProspectusResource.php
app/Models/Prospectus.php
database/factories/ProspectusFactory.php
database/migrations/2020_11_06_013617_create_prospectuses_table.php
database/seeders/DatabaseSeeder.php
database/seeders/ProspectusSeeder.php
routes/api.php

Please review my work, thank you.

Prospectus

---

app/Http/Controllers/API/EnrollController.php
app/Http/Requests/StoreEnrollRequest.php
app/Http/Requests/UpdateEnrollRequest.php
app/Http/Resources/EnrollResource.php
app/Models/Enroll.php
database/factories/EnrollFactory.php
database/migrations/2020_11_06_033308_create_enrolls_table.php
database/seeders/DatabaseSeeder.php
database/seeders/EnrollSeeder.php
routes/api.php

Enroll CRUD

---

app/Http/Controllers/API/ScheduleController.php
app/Http/Requests/StoreScheduleRequest.php
app/Http/Requests/UpdateScheduleRequest.php
app/Http/Resources/ScheduleResource.php
app/Models/Schedule.php
app/Services/ScheduleService.php
database/factories/ScheduleFactory.php
database/migrations/2020_11_17_112905_create_schedules_table.php
database/seeders/DatabaseSeeder.php
database/seeders/ScheduleSeeder.php
routes/api.php

CU-4xqw05_SCHEDULE_Nikko-Lumahang

---

app/Http/Controllers/API/AttendanceController.php
app/Http/Requests/StoreAttendanceRequest.php
app/Http/Requests/UpdateAttendanceRequest.php
app/Http/Resources/AttendanceResource.php
app/Models/Attendance.php
database/factories/AttendanceFactory.php
database/migrations/2020_11_18_101511_create_attendances_table.php
database/seeders/AttendanceSeeder.php
database/seeders/DatabaseSeeder.php
routes/api.php

Please review my work, thanks.

Attendance

---

app/Http/Controllers/Auth/Employee/LoginController.php
app/Http/Controllers/Auth/HomeController.php
app/Http/Kernel.php
app/Http/Middleware/Admin.php
app/Http/Middleware/EnrollmentOfficer.php
app/Http/Middleware/Principal.php
app/Http/Middleware/Registrar.php
app/Http/Middleware/Teacher.php
app/Providers/RouteServiceProvider.php
resources/views/admin/home.blade.php
resources/views/admin/layouts/app.blade.php
resources/views/auth/employee-login.blade.php
resources/views/enrollment-officer/home.blade.php
resources/views/enrollment-officer/layouts/app.blade.php
resources/views/principal/home.blade.php
resources/views/principal/layouts/app.blade.php
resources/views/registrar/home.blade.php
resources/views/registrar/layouts/app.blade.php
resources/views/teacher/home.blade.php
resources/views/teacher/layouts/app.blade.php
routes/admin.php
routes/enrollment_officer.php
routes/principal.php
routes/registrar.php
routes/teacher.php
routes/web.php

Create Employee Login Page

---

public/0.js
public/js/app.js
resources/js/pages/registrar/Dashboard.vue
resources/js/router/index.js
resources/js/router/modules/registrar.js
resources/views/includes/footer.blade.php
resources/views/registrar/home.blade.php
resources/views/registrar/includes/header.blade.php
resources/views/registrar/includes/sidebar.blade.php
resources/views/registrar/layouts/app.blade.php
routes/registrar.php

Create Registrar Dashboard

---

composer.lock
public/1.js
resources/js/pages/teacher/Dashboard.vue
resources/js/router/index.js
resources/js/router/modules/teacher.js
resources/views/registrar/includes/sidebar.blade.php
resources/views/teacher/home.blade.php
resources/views/teacher/includes/header.blade.php
resources/views/teacher/includes/sidebar.blade.php
resources/views/teacher/layouts/app.blade.php
routes/teacher.php

Please review my work, thanks.

Create teacher dashboard

---

package-lock.json
package.json
public/0.js
public/1.js
public/js/app.js
resources/js/app.js
resources/js/pages/registrar/Dashboard.vue
resources/js/pages/teacher/Dashboard.vue

setup plugins

---

app/Http/Controllers/API/SubjectController.php
resources/js/components/registrar/SubjectModal.vue
resources/js/pages/registrar/Subject.vue
resources/js/router/index.js
resources/js/router/modules/registrar.js
resources/views/registrar/includes/sidebar.blade.php
routes/api.php
routes/registrar.php

Create Subject CRUD UI for registrar module

---

public/0.js
public/2.js
public/js/app.js
resources/views/registrar/home.blade.php
resources/views/teacher/home.blade.php

Add Progress Bar

---

app/Http/Controllers/API/TrackController.php
public/1.js
public/3.js
public/js/app.js
resources/js/components/registrar/TrackModal.vue
resources/js/pages/registrar/Track.vue
resources/js/router/index.js
resources/js/router/modules/registrar.js
resources/views/registrar/includes/sidebar.blade.php
routes/api.php
routes/registrar.php

Create Track CRUD UI for registrar module

---

app/Http/Controllers/API/SectionController.php
app/Http/Controllers/API/TrackController.php
app/Http/Requests/StoreSectionRequest.php
app/Models/Section.php
public/3.js
public/4.js
public/js/app.js
resources/js/components/registrar/SectionModal.vue
resources/js/pages/registrar/Section.vue
resources/js/router/index.js
resources/js/router/modules/registrar.js
resources/views/registrar/includes/sidebar.blade.php
routes/api.php
routes/registrar.php

Create Section CRUD UI for registrar module

---

app/Http/Controllers/API/UserController.php
app/Models/Schedule.php
app/Models/User.php
routes/teacher.php

API to get teacher schedules with grades

---

app/Http/Controllers/API/UserController.php
app/Models/Attendance.php
app/Models/Grade.php
app/Models/Guardian.php
app/Models/Schedule.php
app/Models/Section.php
app/Models/Student.php
app/Models/StudentRemark.php
app/Models/Subject.php
app/Models/Track.php
app/Models/User.php

create API for schedules that returns the data of a student

---

public/js/app.js
resources/js/pages/enrollment-officer/index.vue
resources/js/router/index.js
resources/js/router/modules/enrollment-officer.js
resources/views/enrollment-officer/home.blade.php
resources/views/enrollment-officer/includes/header.blade.php
resources/views/enrollment-officer/includes/sidebar.blade.php
resources/views/enrollment-officer/layouts/app.blade.php
routes/enrollment_officer.php

Create Enrollment Officer page

---

app/Http/Controllers/Auth/Student/HomeController.php
app/Http/Controllers/Auth/Student/LoginController.php
app/Http/Kernel.php
app/Http/Middleware/EnsureEmailIsVerifiedOfStudent.php
app/Http/Middleware/RedirectIfNotStudent.php
app/Http/Middleware/RedirectIfStudent.php
app/Providers/RouteServiceProvider.php
config/auth.php
resources/views/student/auth/login.blade.php
resources/views/student/home.blade.php
resources/views/student/layouts/app.blade.php
routes/student.php

Create Student Login Page 
